var charArray=[],pathArray=[],textArray=[],currentStrokeIndex=0,currentCharIndex=0,ieVersion=getInternetExplorerVersion(),svgRect=null,pageXOffset=null,pageYOffset=null,svgRoot=null,userStrokeRoot=null,mouseIsDown=!1,currentStroke=null,prevMouseX=0,prevMouseY=0,failedPrevStroke=!1,mistakeCount=0,totalRed=0,totalYellow=0,tutorialMode=!1,svgNS="http://www.w3.org/2000/svg";
function LoadSVG(a){charArray=[];pathArray=[];textArray=[];currentCharIndex=currentStrokeIndex=0;ieVersion=getInternetExplorerVersion();userStrokeRoot=svgRoot=pageYOffset=pageXOffset=svgRect=null;mouseIsDown=!1;currentStroke=null;prevMouseY=prevMouseX=0;failedPrevStroke=!1;totalYellow=totalRed=mistakeCount=0;tutorialMode=!1;var b=document.getElementById("kanjiVG");findCharacters(b);findPaths(charArray[currentCharIndex]);svgRoot=document.getElementById("svgRoot");userStrokeRoot=document.getElementById("userStrokes");
svgRoot.addEventListener("touchstart",function(a){svgMouseDown(a,!0)},!1);svgRoot.addEventListener("touchmove",function(a){svgMouseMove(a,!0)},!1);svgRoot.addEventListener("touchend",function(a){svgMouseUp(a,!0)},!1);tutorialMode=a;updateSvgPos(!0)}
function resetStrokes(){stopAnimations();document.getElementById("feedback").style.display="none";hidePaths();resetCharacters();currentCharIndex=currentStrokeIndex=0;currentStroke=null;mouseIsDown=!1;currentStroke=null;prevMouseY=prevMouseX=0;failedPrevStroke=!1;pathArray=[];totalMistakes=totalYellow=totalRed=0;findPaths(charArray[currentCharIndex])}
function updateSvgPos(a){"scrollX"in window?(pageXOffset=window.scrollX,pageYOffset=window.scrollY):20!=ieVersion?(a=GetZoomFactor(),pageXOffset=Math.round(document.documentElement.scrollLeft/a),pageYOffset=Math.round(document.documentElement.scrollTop/a)):"pageXOffset"in window&&null!=window.pageXOffset&&(pageXOffset=window.pageXOffset,pageYOffset=window.pageYOffset);svgRect=$("svgRoot").getBoundingClientRect()}
function GetZoomFactor(){var a=1;document.body.getBoundingClientRect&&(a=document.body.getBoundingClientRect(),a=Math.round((a.right-a.left)/document.body.offsetWidth*100)/100);return a}function hidePaths(){for(var a=0;a<pathArray.length;a++)pathArray[a].setAttribute("stroke-opacity","0"),pathArray[a].setAttribute("stroke","black")}function resetCharacters(){for(var a=0;a<charArray.length;a++)charArray[a].setAttribute("transform","translate(0,0) scale(1)")}
function findPaths(a){a=a.childNodes;for(var b=0;b<a.length;b++)1==a[b].nodeType&&("path"==a[b].tagName&&pathArray.push(a[b]),"text"==a[b].tagName&&textArray.push(a[b]),a[b].hasChildNodes()&&findPaths(a[b]))}function findCharacters(a){a=a.childNodes;for(var b=0;b<a.length;b++)1==a[b].nodeType&&"g"==a[b].tagName&&charArray.push(a[b])}
function svgMouseDown(a,b){null!=currentStroke&&(userStrokeRoot.removeChild(currentStroke),currentStroke=null);mouseIsDown=!0;document.onselectstart=function(){return!1};var c=getMouseOrTouchCoords(b,a);currentStroke=document.createElementNS(svgNS,"path");currentStroke.pathSegList.appendItem(currentStroke.createSVGPathSegMovetoAbs(c.x,c.y));userStrokeRoot.appendChild(currentStroke);11<=ieVersion&&a.preventDefault()}
function getMouseOrTouchCoords(a,b){result=svgRoot.createSVGPoint();!1==a?(result.x=b.pageX,result.y=b.pageY):(result.x=b.changedTouches[0].pageX,result.y=b.changedTouches[0].pageY);updateSvgPos(!1);result.x=(result.x-svgRect.left-pageXOffset)/3;result.y=(result.y-svgRect.top-pageYOffset)/3;return result}
function svgMouseMove(a,b){if(!1!=mouseIsDown&&null!=currentStroke){var c=getMouseOrTouchCoords(b,a);2<distance(c.x,c.y,prevMouseX,prevMouseY)&&(prevMouseX=c.x,prevMouseY=c.y,currentStroke.pathSegList.appendItem(currentStroke.createSVGPathSegLinetoAbs(c.x,c.y)));11<=ieVersion&&a.preventDefault()}}function distance(a,b,c,d){var e=0,f=0,e=c-a,f=d-b;return Math.sqrt(e*e+f*f)}
function svgMouseUp(a,b){if(!1!=mouseIsDown&&null!=currentStroke){mouseIsDown=!1;document.onselectstart=function(){return!0};var c=getMouseOrTouchCoords(b,a);currentStroke.pathSegList.appendItem(currentStroke.createSVGPathSegLinetoAbs(c.x,c.y));processStroke();11<=ieVersion&&a.preventDefault()}}
var helpMessages={threeWrongStrokes:{text:"<strong>Don't worry!</strong>  If you miss a stroke 3 times, a hint will appear in blue, showing you where the next stroke should be drawn.",seen:!1},wrongStroke:{text:"<strong>Try again!</strong> If your stroke is too far off from the correct position, it will turn red and disappear.",seen:!1},correctAfterMiss:{text:"<strong>You got it!</strong>  If you got a stroke wrong previously, then when you do get it right it will stay red.  This is to remind you that you missed it when you grade yourself at the end.",
seen:!1},closeStroke:{text:"<strong>Almost!</strong>  If your stroke is somewhat off from the correct position, it will be colored dark yellow.  This is a reminder to think about whether you really got this stroke right when you grade yourself at the end.",seen:!1},correctStroke:{text:"<strong>Good job!</strong>  When you get a stroke close enough on the first try, it will turn black and move to the correct position within the box.",seen:!1},finishedCharacter:{text:"<strong>Great work!</strong>  When you finish a character, it will get smaller and move off to the side so you can see all the characters you've written.",
seen:!1},tooManyStrokes:{text:"<strong>Whoa!</strong>  If you try to make another stroke when you've already finished a character, your stroke will turn red and disappear.  This helps you learn to distinguish similar characters.",seen:!1}};function showHelpMessage(a){tutorialMode&&(a=helpMessages[a])&&!a.seen&&(setMessage(a.text),a.seen=!0)}function setMessage(a){document.getElementById("scriptText").innerHTML=a;document.getElementById("feedback").style.display="block"}
function clearMessage(){document.getElementById("feedback").style.display="none"}
function processStroke(){var a=currentStroke.getTotalLength();tutorialMode&&clearMessage();if(2>a)userStrokeRoot.removeChild(currentStroke),currentStroke=null;else if(currentStrokeIndex>=pathArray.length){currentStroke.setAttribute("stroke","red ");++totalRed;var b=[new StrokeOpacityAction(currentStroke,1,0)];doAnimation(b,0.5);pathArray[currentStrokeIndex-1].setAttribute("stroke","red ");showHelpMessage("tooManyStrokes")}else{var c=currentStroke.getPointAtLength(0),d=currentStroke.getPointAtLength(a),
b=180*Math.atan2(d.y-c.y,d.x-c.x)/Math.PI,e=(d.x+c.x)/2,f=(d.y+c.y)/2,g=pathArray[currentStrokeIndex],h=g.getTotalLength(),k=g.getPointAtLength(0),l=g.getPointAtLength(h),n=180*Math.atan2(l.y-k.y,l.x-k.x)/Math.PI,p=(l.x+k.x)/2,q=(l.y+k.y)/2;SAMPLE_COUNT=20;var m=getSamples(g,h,h/2),m=getSlopes(m),a=getSamples(currentStroke,a,h/2),a=getSlopes(a),a=meanOfArray(variance(m,a)),h=distance(e,f,p,q)/20,h=h*h,m=distance(k.x,k.y,l.x,l.y)/distance(c.x,c.y,d.x,d.y),c=distance(c.x,c.y,d.x,d.y)/distance(k.x,k.y,
l.x,l.y);Math.abs(m-1);d=a+h;4<d?(currentStroke.setAttribute("stroke","red "),++totalRed,++mistakeCount,3==mistakeCount?(showHint(!0),showHelpMessage("threeWrongStrokes")):showHelpMessage("wrongStroke"),b=[new StrokeOpacityAction(currentStroke,1,0)],doAnimation(b,0.5),failedPrevStroke=!0):(!0==failedPrevStroke?(currentStroke.setAttribute("stroke","red"),g.setAttribute("stroke","red"),++totalRed,showHelpMessage("correctAfterMiss")):2<d?(currentStroke.setAttribute("stroke","#635f00"),g.setAttribute("stroke",
"#635f00"),++totalYellow,showHelpMessage("closeStroke")):(currentStroke.setAttribute("stroke","black"),showHelpMessage("correctStroke")),failedPrevStroke=!1,mistakeCount=0,b=[new MatrixAction(currentStroke,0,p-e,0,q-f,1,m,0,n-b,e,f),new MatrixAction(g,e-p,0,f-q,0,c,1,b-n,0,p,q),new StrokeOpacityAction(currentStroke,1,0),new StrokeOpacityAction(g,0,1)],doAnimation(b,0.5),currentStrokeIndex++,currentStroke=null,1<charArray.length&&currentStrokeIndex>=pathArray.length&&(currentChar=charArray[currentCharIndex],
b=97,e=2+10*currentCharIndex,f=0,"true"==currentChar.getAttribute("data-rotate")&&(f=90,b+=11),b=[new MatrixAction(currentChar,0,b,0,e,1,0.1,0,f,0,0)],doAnimationDelayed(b,0.5,0.5),currentCharIndex++,currentStroke=null,currentCharIndex<charArray.length&&findPaths(charArray[currentCharIndex]),showHelpMessage("finishedCharacter")))}}
function showHint(a){if(!(1<charArray.length&&currentStrokeIndex>=pathArray.length)){failedPrevStroke=!0;var b=pathArray[currentStrokeIndex];a=b.getTotalLength();var c=a.toString();b.setAttribute("stroke","#3991d4");b.setAttribute("stroke-dasharray",c+","+c);b=[new StrokeOpacityAction(b,0,0.5),new DashOffsetAction(b,a,0)];doAnimation(b,a/60)}}
function showRemainingStrokes(){for(var a=[];currentCharIndex<charArray.length;){for(;currentStrokeIndex<pathArray.length;){var b=pathArray[currentStrokeIndex],c=b.getTotalLength(),d=c.toString();b.setAttribute("visibility","hidden");b.setAttribute("stroke","red ");b.setAttribute("stroke-dasharray",d+","+d);++totalRed;d=new ActionGroup;d.actions.push(new StrokeOpacityAction(b,0,1));d.actions.push(new DashOffsetAction(b,c,0));d.duration=c/120;a.push(d);++currentStrokeIndex}if(1<charArray.length&&currentStrokeIndex>=
pathArray.length){currentChar=charArray[currentCharIndex];var b=97,c=2+10*currentCharIndex,e=0;"true"==currentChar.getAttribute("data-rotate")&&(e=90,b+=11);d=new ActionGroup;d.actions.push(new MatrixAction(currentChar,0,b,0,c,1,0.1,0,e,0,0));d.duration=0.25;a.push(d)}currentCharIndex++;currentCharIndex<charArray.length&&findPaths(charArray[currentCharIndex])}d=new ActionGroup;d.duration=0.75;0<totalRed?d.actions.push(new GlowAction($("glowMatrix"),1,0,0,$("kanjiVG"))):0<totalYellow?d.actions.push(new GlowAction($("glowMatrix"),
0.5,0.5,0,$("kanjiVG"))):d.actions.push(new GlowAction($("glowMatrix"),0,0.5,0,$("kanjiVG")));a.push(d);doAnimationSequential(a,0.4)}function StrokeOpacityAction(a,b,c){this.stroke=a;this.from=b;this.to=c}StrokeOpacityAction.prototype.execute=function(a){a=lerp(this.from,this.to,a);this.stroke.setAttribute("stroke-opacity",a);0.1>=a?this.stroke.setAttribute("visibility","hidden"):this.stroke.setAttribute("visibility","visible")};
function TransformAction(a,b,c,d,e){this.target=a;this.fromX=b;this.fromY=c;this.toX=d;this.toY=e}TransformAction.prototype.execute=function(a){var b=lerp(this.fromX,this.toX,a);a=lerp(this.fromY,this.toY,a);this.target.setAttribute("transform","translate("+b.toString()+","+a.toString()+")")};function RotateAction(a,b,c){this.target=a;this.from=b;this.to=c}RotateAction.prototype.execute=function(a){a=lerp(this.from,this.to,a);this.target.setAttribute("transform","rotate("+a.toString()+")")};
function ScaleAction(a,b,c){this.target=a;this.from=b;this.to=c}ScaleAction.prototype.execute=function(a){a=lerp(this.from,this.to,a);this.target.setAttribute("transform","scale("+a.toString()+")")};function MatrixAction(a,b,c,d,e,f,g,h,k,l,n){this.target=a;this.fromX=b;this.toX=c;this.fromY=d;this.toY=e;this.fromS=f;this.toS=g;this.fromR=h;this.toR=k;this.centerX=l;this.centerY=n}
MatrixAction.prototype.execute=function(a){var b=lerp(this.fromX,this.toX,a),c=lerp(this.fromY,this.toY,a),d=lerp(this.fromS,this.toS,a);a=lerp(this.fromR,this.toR,a);var e=svgRoot.createSVGMatrix(),e=e.translate(b,c),e=e.translate(this.centerX,this.centerY),e=e.rotate(a),e=e.scale(d),e=e.translate(-this.centerX,-this.centerY);this.target.setAttribute("transform","matrix("+e.a.toString()+", "+e.b.toString()+", "+e.c.toString()+", "+e.d.toString()+", "+e.e.toString()+", "+e.f.toString()+")")};
function GlowAction(a,b,c,d,e){this.target=a;this.r=b;this.g=c;this.b=d;this.filterTarget=e}GlowAction.prototype.execute=function(a){a*=2;1<a&&(a=1-(a-1));0.05>a?(a=0,this.filterTarget.setAttribute("filter","")):this.filterTarget.setAttribute("filter","url(#glow)");a*=1.5;this.target.setAttribute("values","0 0 0 "+this.r+" 0 0 0 0 "+this.g+" 0 0 0 0 "+this.b+" 0 0 0 0 "+a+" 0")};function DashOffsetAction(a,b,c){this.target=a;this.from=b;this.to=c}
DashOffsetAction.prototype.execute=function(a){a=lerp(this.from,this.to,a);this.target.setAttribute("stroke-dashoffset",a.toString())};function lerp(a,b,c){return a*(1-c)+b*c}var activeIntervals=[];function doAnimation(a,b){var c=0,d=setInterval(function(){c+=50/(1E3*b);if(1<c){var e=activeIntervals.indexOf(d);-1<e&&activeIntervals.splice(e,1);clearInterval(d);c=1}for(e=0;e<a.length;e++)a[e].execute(c)},50);activeIntervals.push(d)}function ActionGroup(){this.duration=1;this.actions=[]}
function doAnimationSequential(a){var b=0,c=0,d=a[0].duration,e=setInterval(function(){c+=50/(1E3*d);var f=!1;1<c&&(f=!0,c=1);for(var g=0;g<a[b].actions.length;g++)a[b].actions[g].execute(c);f&&(b>=a.length-1?(f=activeIntervals.indexOf(e),-1<f&&activeIntervals.splice(f,1),clearInterval(e)):(c=0,b+=1,d=a[b].duration))},50);activeIntervals.push(e)}var activeTimeouts=[];
function doAnimationDelayed(a,b,c){var d=setTimeout(function(){doAnimation(a,b);var c=activeTimeouts.indexOf(d);-1<c&&activeTimeouts.splice(c,1)},1E3*c);activeTimeouts.push(d)}
function stopAnimations(){for(var a=activeIntervals.length,b=0;b<a;++b)clearInterval(activeIntervals[b]);activeIntervals=[];a=activeTimeouts.length;for(b=0;b<a;++b)clearTimeout(activeTimeouts[b]);activeTimeouts=[];$("kanjiVG").setAttribute("filter","");$("glowMatrix").setAttribute("values","0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0")}function isAnimationActive(){return 0<activeIntervals.length}function slope(a,b){return 180*Math.atan2(b.y-a.y,b.x-a.x)/Math.PI}
function meanOfArray(a){for(var b=a.length,c=0,d=0;d<b;++d)c+=a[d];return c/b}function getSlopes(a){var b=a.length,c=[];c.push(slope(a[0],a[1]));for(var d=1;d<b-1;++d)c.push(slope(a[d-1],a[d+1]));c.push(slope(a[b-2],a[b-1]));for(d=0;4>d;++d)c=smoothResults(c);return c}function getSamples(a,b,c){b/=c;for(var d=[],e=0;e<c;++e)d.push(a.getPointAtLength(e*b));return d}
function smoothResults(a){for(var b=a.length,c=[],d=0;d<b;++d){var e=3.8771E-4*sampleClipped(a,d-3,b)+0.01330373*sampleClipped(a,d-2,b)+0.11098164*sampleClipped(a,d-1,b)+0.22508352*sampleClipped(a,d,b)+0.11098164*sampleClipped(a,d+1,b)+0.01330373*sampleClipped(a,d+2,b)+3.8771E-4*sampleClipped(a,d+3,b);c.push(e)}return c}function sampleClipped(a,b,c){return 0>b?a[0]:b>=c?a[c-1]:a[b]}function variance(a,b){for(var c=a.length,d=[],e=0;e<c;++e)d.push(Math.abs(a[e]-b[e]));return d}
function getInternetExplorerVersion(){var a=20;if("Microsoft Internet Explorer"==navigator.appName){var b=navigator.userAgent,c=/MSIE ([0-9]{1,}[.0-9]{0,})/;null!=c.exec(b)&&(a=parseFloat(RegExp.$1))}else"Netscape"==navigator.appName&&(b=navigator.userAgent,c=/Trident\/.*rv:([0-9]{1,}[.0-9]{0,})/,null!=c.exec(b)&&(a=parseFloat(RegExp.$1)));return a}function $(a){return document.getElementById(a)};
